apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 2   # number of Pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container                # 👈 container name (matches Jenkins pipeline)
        image: 578294758767.dkr.ecr.us-east-1.amazonaws.com/my-img:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  type: LoadBalancer                      # creates an AWS ELB
  selector:
    app: my-app
  ports:
    - port: 80                            # service port (external)
      targetPort: 8080                    # forwards to containerPort
